export const EVENTS = {
  SOCKET_CONNECTION: "SOCKET_CONNECTION",
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  SEND_MESSAGE: "SEND_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
  TYPING: "TYPING",
  STOP_TYPING: "STOP_TYPING",
  SEND_PRIVATE_MESSAGE: "SEND_PRIVATE_MESSAGE",
  RECEIVE_PRIVATE_MESSAGE: "RECEIVE_PRIVATE_MESSAGE",
  JOIN_ALL_ROOM: "JOIN_ALL_ROOM",
  USER_JOINED: "USER_JOINED",
  SET_USER_INFO: "SET_USER_INFO",
};
